package ustc.sse.assistant.event;

public interface EventConstant {
	int EVENT_ALARM_TYPE_RING = 0;
	int EVENT_ALARM_TYPE_VIBRATE = 1;
	int EVENT_ALARM_TYPE_NOTIFICATION = 2;
	
	int EVENT_TODAY_REMIND_TIME_NONE = 0;
	int EVENT_TODAY_REMIND_TIME_ONE_MINUTE = 1;
	int EVENT_TODAY_REMIND_TIME_FIVE_MINUTE = 2;
	int EVENT_TODAY_REMIND_TIME_TEN_MINUTE = 3;
	int EVENT_TODAY_REMIND_TIME_FIFTEEN_MINUTE = 4;
	int EVENT_TODAY_REMIND_TIME_TWENTY_MINUTE = 5;
	int EVENT_TODAY_REMIND_TIME_THIRTY_MINUTE = 6;
	int EVENT_TODAY_REMIND_TIME_FOURTYFIVE_MINUTE = 7;
	int EVENT_TODAY_REMIND_TIME_ONE_HOUR = 8;
	int EVENT_TODAY_REMIND_TIME_TWO_HOUR = 9;
	int EVENT_TODAY_REMIND_TIME_THREE_HOUR = 10;
	int EVENT_TODAY_REMIND_TIME_SIX_HOUR = 11;
	int EVENT_TODAY_REMIND_TIME_TWELVE_HOUR = 12;
}
